# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_batch_batch_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='sequence_prob',
            field=models.FloatField(default=0.0),
        ),
    ]
