# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-21 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20180321_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='record_data',
            new_name='record_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batch_name',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_no',
            field=models.CharField(default='000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='model',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='specification',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
