# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20180321_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='forge_rate',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='mistake_rate',
            field=models.FloatField(default=-1.0),
        ),
    ]
