# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20180328_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='forge_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='mistake_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
