# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-17 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20180328_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='range_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
